server:
  port: 8080
spring:
  application:
    name: "msAutenticacion"
  devtools:
    add-properties: false
  profiles:
    include: null

# Configuración personalizada para R2DBC PostgreSQL
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: autenticacion_db
    schema: public
    username: test
    password: test

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    co.com.msautenticacion: DEBUG
    org.springframework.r2dbc: DEBUG
